package scanner

import (
	"os"
	"path/filepath"
	"testing"
)

func TestClassifyLockfiles(t *testing.T) {
	c := NewClassifier()
	lockfiles := []string{
		"package-lock.json",
		"yarn.lock",
		"Cargo.lock",
		"Gemfile.lock",
		"poetry.lock",
		"go.sum",
		"pnpm-lock.yaml",
	}
	for _, name := range lockfiles {
		cl := c.ClassifyPath(name, false)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, cl.Level)
		}
		if cl.Category != CategoryLockfile {
			t.Errorf("%s: expected CategoryLockfile, got %q", name, cl.Category)
		}
	}
}

func TestClassifyDependencyDirs(t *testing.T) {
	c := NewClassifier()
	dirs := []string{"node_modules", "vendor", ".venv", "venv"}
	for _, name := range dirs {
		cl := c.ClassifyPath(name, true)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s/: expected NoiseLevelRed, got %d", name, cl.Level)
		}
		if cl.Category != CategoryDependency {
			t.Errorf("%s/: expected CategoryDependency, got %q", name, cl.Category)
		}
	}
}

func TestClassifyBuildDirs(t *testing.T) {
	c := NewClassifier()
	dirs := []string{"dist", "build", "out", "target"}
	for _, name := range dirs {
		cl := c.ClassifyPath(name, true)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s/: expected NoiseLevelRed, got %d", name, cl.Level)
		}
		if cl.Category != CategoryBuildArtifact {
			t.Errorf("%s/: expected CategoryBuildArtifact, got %q", name, cl.Category)
		}
	}
}

func TestClassifyMinifiedFiles(t *testing.T) {
	c := NewClassifier()
	files := []string{"bundle.min.js", "styles.min.css"}
	for _, name := range files {
		cl := c.ClassifyPath(name, false)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, cl.Level)
		}
		if cl.Category != CategoryBuildArtifact {
			t.Errorf("%s: expected CategoryBuildArtifact, got %q", name, cl.Category)
		}
	}
}

func TestClassifyGeneratedName(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name    string
		pattern string
	}{
		{"api.pb.go", "*.pb.go"},
		{"schema.generated.ts", "*.generated.*"},
	}
	for _, tc := range cases {
		cl := c.ClassifyPath(tc.name, false)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, cl.Level)
		}
		if cl.Category != CategoryGenerated {
			t.Errorf("%s: expected CategoryGenerated, got %q", tc.name, cl.Category)
		}
		if cl.Pattern != tc.pattern {
			t.Errorf("%s: expected pattern %q, got %q", tc.name, tc.pattern, cl.Pattern)
		}
	}
}

func TestClassifyTestFiles(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name    string
		pattern string
	}{
		{"foo.test.ts", "*.test.ts"},
		{"bar.spec.js", "*.spec.js"},
		{"baz_test.go", "*_test.go"},
	}
	for _, tc := range cases {
		cl := c.ClassifyPath(tc.name, false)
		if cl.Level != NoiseLevelYellow {
			t.Errorf("%s: expected NoiseLevelYellow, got %d", tc.name, cl.Level)
		}
		if cl.Category != CategoryTestFile {
			t.Errorf("%s: expected CategoryTestFile, got %q", tc.name, cl.Category)
		}
		if cl.Pattern != tc.pattern {
			t.Errorf("%s: expected pattern %q, got %q", tc.name, tc.pattern, cl.Pattern)
		}
	}
}

func TestClassifyIDENoise(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name  string
		isDir bool
	}{
		{".DS_Store", false},
		{".idea", true},
		{".vscode", true},
	}
	for _, tc := range cases {
		cl := c.ClassifyPath(tc.name, tc.isDir)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, cl.Level)
		}
		if cl.Category != CategoryIDEOS {
			t.Errorf("%s: expected CategoryIDEOS, got %q", tc.name, cl.Category)
		}
	}
}

func TestClassifySignalFiles(t *testing.T) {
	c := NewClassifier()
	files := []string{"main.go", "README.md", "server.py", "index.ts"}
	for _, name := range files {
		cl := c.ClassifyPath(name, false)
		if cl.Level != NoiseLevelNone {
			t.Errorf("%s: expected NoiseLevelNone (signal), got %d", name, cl.Level)
		}
	}
}

func TestClassifyBinaryExtensions(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name    string
		pattern string
	}{
		{"image.png", "*.png"},
		{"photo.jpg", "*.jpg"},
		{"archive.zip", "*.zip"},
		{"app.exe", "*.exe"},
	}
	for _, tc := range cases {
		cl := c.ClassifyPath(tc.name, false)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, cl.Level)
		}
		if cl.Category != CategoryBinary {
			t.Errorf("%s: expected CategoryBinary, got %q", tc.name, cl.Category)
		}
		if cl.Pattern != tc.pattern {
			t.Errorf("%s: expected pattern %q, got %q", tc.name, tc.pattern, cl.Pattern)
		}
	}
}

func TestClassifyGeneratedContent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "generated.go")
	content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	c := NewClassifier()
	cl := c.ClassifyPath(path, false)
	if cl.Level != NoiseLevelRed {
		t.Errorf("expected NoiseLevelRed for generated content, got %d", cl.Level)
	}
	if cl.Category != CategoryGenerated {
		t.Errorf("expected CategoryGenerated, got %q", cl.Category)
	}
}

func TestClassifyBinaryContent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "file.dat")
	content := []byte{0x7f, 0x45, 0x4c, 0x46, 0x00, 0x01, 0x02, 0x03}
	if err := os.WriteFile(path, content, 0644); err != nil {
		t.Fatal(err)
	}

	c := NewClassifier()
	cl := c.ClassifyPath(path, false)
	if cl.Level != NoiseLevelRed {
		t.Errorf("expected NoiseLevelRed for binary content, got %d", cl.Level)
	}
	if cl.Category != CategoryBinary {
		t.Errorf("expected CategoryBinary, got %q", cl.Category)
	}
}

func TestClassifyTestArtifacts(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name  string
		isDir bool
	}{
		{"coverage", true},
		{"__snapshots__", true},
		{"component.snap", false},
	}
	for _, tc := range cases {
		cl := c.ClassifyPath(tc.name, tc.isDir)
		if cl.Level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, cl.Level)
		}
		if cl.Category != CategoryTestArtifact {
			t.Errorf("%s: expected CategoryTestArtifact, got %q", tc.name, cl.Category)
		}
	}
}
