package scanner

import (
	"os"
	"path/filepath"
	"testing"
)

func TestClassifyLockfiles(t *testing.T) {
	c := NewClassifier()
	lockfiles := []string{
		"package-lock.json",
		"yarn.lock",
		"Cargo.lock",
		"Gemfile.lock",
		"poetry.lock",
		"go.sum",
		"pnpm-lock.yaml",
	}
	for _, name := range lockfiles {
		level, cat := c.ClassifyPath(name, false)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryLockfile {
			t.Errorf("%s: expected CategoryLockfile, got %q", name, cat)
		}
	}
}

func TestClassifyDependencyDirs(t *testing.T) {
	c := NewClassifier()
	dirs := []string{"node_modules", "vendor", ".venv", "venv"}
	for _, name := range dirs {
		level, cat := c.ClassifyPath(name, true)
		if level != NoiseLevelRed {
			t.Errorf("%s/: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryDependency {
			t.Errorf("%s/: expected CategoryDependency, got %q", name, cat)
		}
	}
}

func TestClassifyBuildDirs(t *testing.T) {
	c := NewClassifier()
	dirs := []string{"dist", "build", "out", "target"}
	for _, name := range dirs {
		level, cat := c.ClassifyPath(name, true)
		if level != NoiseLevelRed {
			t.Errorf("%s/: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryBuildArtifact {
			t.Errorf("%s/: expected CategoryBuildArtifact, got %q", name, cat)
		}
	}
}

func TestClassifyMinifiedFiles(t *testing.T) {
	c := NewClassifier()
	files := []string{"bundle.min.js", "styles.min.css"}
	for _, name := range files {
		level, cat := c.ClassifyPath(name, false)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryBuildArtifact {
			t.Errorf("%s: expected CategoryBuildArtifact, got %q", name, cat)
		}
	}
}

func TestClassifyGeneratedName(t *testing.T) {
	c := NewClassifier()
	files := []string{"api.pb.go", "schema.generated.ts"}
	for _, name := range files {
		level, cat := c.ClassifyPath(name, false)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryGenerated {
			t.Errorf("%s: expected CategoryGenerated, got %q", name, cat)
		}
	}
}

func TestClassifyTestFiles(t *testing.T) {
	c := NewClassifier()
	files := []string{"foo.test.ts", "bar.spec.js", "baz_test.go"}
	for _, name := range files {
		level, cat := c.ClassifyPath(name, false)
		if level != NoiseLevelYellow {
			t.Errorf("%s: expected NoiseLevelYellow, got %d", name, level)
		}
		if cat != CategoryTestFile {
			t.Errorf("%s: expected CategoryTestFile, got %q", name, cat)
		}
	}
}

func TestClassifyIDENoise(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name  string
		isDir bool
	}{
		{".DS_Store", false},
		{".idea", true},
		{".vscode", true},
	}
	for _, tc := range cases {
		level, cat := c.ClassifyPath(tc.name, tc.isDir)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, level)
		}
		if cat != CategoryIDEOS {
			t.Errorf("%s: expected CategoryIDEOS, got %q", tc.name, cat)
		}
	}
}

func TestClassifySignalFiles(t *testing.T) {
	c := NewClassifier()
	files := []string{"main.go", "README.md", "server.py", "index.ts"}
	for _, name := range files {
		level, _ := c.ClassifyPath(name, false)
		if level != NoiseLevelNone {
			t.Errorf("%s: expected NoiseLevelNone (signal), got %d", name, level)
		}
	}
}

func TestClassifyBinaryExtensions(t *testing.T) {
	c := NewClassifier()
	files := []string{"image.png", "photo.jpg", "archive.zip", "app.exe"}
	for _, name := range files {
		level, cat := c.ClassifyPath(name, false)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", name, level)
		}
		if cat != CategoryBinary {
			t.Errorf("%s: expected CategoryBinary, got %q", name, cat)
		}
	}
}

func TestClassifyGeneratedContent(t *testing.T) {
	// Create a temp file with generated marker
	dir := t.TempDir()
	path := filepath.Join(dir, "generated.go")
	content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	c := NewClassifier()
	level, cat := c.ClassifyPath(path, false)
	if level != NoiseLevelRed {
		t.Errorf("expected NoiseLevelRed for generated content, got %d", level)
	}
	if cat != CategoryGenerated {
		t.Errorf("expected CategoryGenerated, got %q", cat)
	}
}

func TestClassifyBinaryContent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "file.dat")
	// Write binary content with null bytes
	content := []byte{0x7f, 0x45, 0x4c, 0x46, 0x00, 0x01, 0x02, 0x03}
	if err := os.WriteFile(path, content, 0644); err != nil {
		t.Fatal(err)
	}

	c := NewClassifier()
	level, cat := c.ClassifyPath(path, false)
	if level != NoiseLevelRed {
		t.Errorf("expected NoiseLevelRed for binary content, got %d", level)
	}
	if cat != CategoryBinary {
		t.Errorf("expected CategoryBinary, got %q", cat)
	}
}

func TestClassifyTestArtifacts(t *testing.T) {
	c := NewClassifier()
	cases := []struct {
		name  string
		isDir bool
	}{
		{"coverage", true},
		{"__snapshots__", true},
		{"component.snap", false},
	}
	for _, tc := range cases {
		level, cat := c.ClassifyPath(tc.name, tc.isDir)
		if level != NoiseLevelRed {
			t.Errorf("%s: expected NoiseLevelRed, got %d", tc.name, level)
		}
		if cat != CategoryTestArtifact {
			t.Errorf("%s: expected CategoryTestArtifact, got %q", tc.name, cat)
		}
	}
}
