// Package generator writes ignore files from scan results.
package generator

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/arniesaha/ctx-ignore/internal/scanner"
)

// Options controls which files to generate.
type Options struct {
	WriteContextIgnore  bool
	WriteClaudeIgnore   bool
	WriteCursorIgnore   bool
	WriteCopilotIgnore  bool
	WriteWindsurfIgnore bool
	PatchGitIgnore      bool
	DryRun              bool
	OutputDir           string
}

// DefaultOptions returns the default generation options.
func DefaultOptions() Options {
	return Options{
		WriteContextIgnore:  true,
		WriteClaudeIgnore:   true,
		WriteCursorIgnore:   true,
		WriteCopilotIgnore:  true,
		WriteWindsurfIgnore: true,
		PatchGitIgnore:      false,
		DryRun:              false,
	}
}

// Generate creates ignore files based on scan results.
func Generate(result *scanner.ScanResult, opts Options) ([]string, error) {
	dir := opts.OutputDir
	if dir == "" {
		dir = result.Root
	}

	patterns := buildPatterns(result)
	var generated []string

	if opts.WriteContextIgnore {
		content := buildContextIgnore(patterns)
		if !opts.DryRun {
			path := filepath.Join(dir, ".contextignore")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return generated, fmt.Errorf("writing .contextignore: %w", err)
			}
		}
		generated = append(generated, ".contextignore")
	}

	if opts.WriteClaudeIgnore {
		content := buildDerivedIgnore(patterns)
		if !opts.DryRun {
			path := filepath.Join(dir, ".claudeignore")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return generated, fmt.Errorf("writing .claudeignore: %w", err)
			}
		}
		generated = append(generated, ".claudeignore")
	}

	if opts.WriteCursorIgnore {
		content := buildDerivedIgnore(patterns)
		if !opts.DryRun {
			path := filepath.Join(dir, ".cursorignore")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return generated, fmt.Errorf("writing .cursorignore: %w", err)
			}
		}
		generated = append(generated, ".cursorignore")
	}

	if opts.WriteCopilotIgnore {
		content := buildDerivedIgnore(patterns)
		if !opts.DryRun {
			path := filepath.Join(dir, ".copilotignore")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return generated, fmt.Errorf("writing .copilotignore: %w", err)
			}
		}
		generated = append(generated, ".copilotignore")
	}

	if opts.WriteWindsurfIgnore {
		content := buildDerivedIgnore(patterns)
		if !opts.DryRun {
			path := filepath.Join(dir, ".windsurfignore")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				return generated, fmt.Errorf("writing .windsurfignore: %w", err)
			}
		}
		generated = append(generated, ".windsurfignore")
	}

	if opts.PatchGitIgnore {
		if !opts.DryRun {
			if err := patchGitIgnore(dir, patterns); err != nil {
				return generated, fmt.Errorf("patching .gitignore: %w", err)
			}
		}
		generated = append(generated, ".gitignore (patched)")
	}

	return generated, nil
}

type patternGroup struct {
	comment  string
	patterns []string
}

func buildPatterns(result *scanner.ScanResult) []patternGroup {
	// Group patterns by category
	groups := map[scanner.NoiseCategory][]string{}
	for _, p := range result.NoisePatterns {
		groups[p.Category] = append(groups[p.Category], p.Pattern)
	}

	order := []struct {
		cat     scanner.NoiseCategory
		comment string
	}{
		{scanner.CategoryLockfile, "Lockfiles — auto-generated, never edit manually"},
		{scanner.CategoryDependency, "Dependencies — never edit, always restorable"},
		{scanner.CategoryBuildArtifact, "Build artifacts — generated output"},
		{scanner.CategoryGenerated, "Generated code — do not edit"},
		{scanner.CategoryTestArtifact, "Test artifacts — coverage, snapshots"},
		{scanner.CategoryBinary, "Binary files — not readable by AI tools"},
		{scanner.CategoryIDEOS, "IDE/OS noise — editor and system files"},
		{scanner.CategoryTestFile, "Test files — optional to ignore"},
	}

	var result2 []patternGroup
	for _, o := range order {
		if pats, ok := groups[o.cat]; ok && len(pats) > 0 {
			result2 = append(result2, patternGroup{
				comment:  o.comment,
				patterns: pats,
			})
		}
	}
	return result2
}

func buildContextIgnore(groups []patternGroup) string {
	var sb strings.Builder
	sb.WriteString("# ctx-ignore: generated by ctx-ignore scan\n")
	sb.WriteString("# Generated: " + time.Now().Format("2006-01-02") + "\n")
	sb.WriteString("# Edit this file to customize what AI tools see in your repo\n")
	sb.WriteString("# .claudeignore, .cursorignore, .copilotignore, and .windsurfignore are derived from this file\n")
	sb.WriteString("\n")

	for _, g := range groups {
		sb.WriteString("# " + g.comment + "\n")
		for _, p := range g.patterns {
			sb.WriteString(p + "\n")
		}
		sb.WriteString("\n")
	}

	return sb.String()
}

func buildDerivedIgnore(groups []patternGroup) string {
	var sb strings.Builder
	for _, g := range groups {
		for _, p := range g.patterns {
			sb.WriteString(p + "\n")
		}
	}
	return sb.String()
}

func patchGitIgnore(dir string, groups []patternGroup) error {
	path := filepath.Join(dir, ".gitignore")
	existing := ""
	data, err := os.ReadFile(path)
	if err == nil {
		existing = string(data)
	}

	// Build set of existing lines for exact matching
	existingLines := map[string]bool{}
	sc := bufio.NewScanner(strings.NewReader(existing))
	for sc.Scan() {
		existingLines[strings.TrimSpace(sc.Text())] = true
	}

	var toAdd []string
	for _, g := range groups {
		for _, p := range g.patterns {
			if !existingLines[p] {
				toAdd = append(toAdd, p)
			}
		}
	}

	if len(toAdd) == 0 {
		return nil
	}

	var sb strings.Builder
	sb.WriteString(existing)
	if existing != "" && !strings.HasSuffix(existing, "\n") {
		sb.WriteString("\n")
	}
	sb.WriteString("\n# ctx-ignore: added by ctx-ignore scan\n")
	for _, p := range toAdd {
		sb.WriteString(p + "\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
