package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arniesaha/ctx-ignore/internal/scanner"
)

func testResult() *scanner.ScanResult {
	return &scanner.ScanResult{
		Root:       "/tmp/test",
		TotalFiles: 10,
		NoisePatterns: []scanner.NoisePattern{
			{Pattern: "package-lock.json", Tokens: 42000, Count: 1, Level: scanner.NoiseLevelRed, Category: scanner.CategoryLockfile},
			{Pattern: "node_modules/", Tokens: 100000, Count: 1, Level: scanner.NoiseLevelRed, Category: scanner.CategoryDependency},
			{Pattern: "*_test.go", Tokens: 5000, Count: 3, Level: scanner.NoiseLevelYellow, Category: scanner.CategoryTestFile},
		},
	}
}

func TestBuildPatternsGroupsByCategory(t *testing.T) {
	result := testResult()
	groups := buildPatterns(result)

	if len(groups) != 3 {
		t.Fatalf("expected 3 groups, got %d", len(groups))
	}

	// Lockfiles should come first per the defined order
	if !strings.Contains(groups[0].comment, "Lockfiles") {
		t.Errorf("first group should be Lockfiles, got %q", groups[0].comment)
	}
	if !strings.Contains(groups[1].comment, "Dependencies") {
		t.Errorf("second group should be Dependencies, got %q", groups[1].comment)
	}
	if !strings.Contains(groups[2].comment, "Test files") {
		t.Errorf("third group should be Test files, got %q", groups[2].comment)
	}
}

func TestBuildContextIgnoreHasHeaderAndComments(t *testing.T) {
	result := testResult()
	groups := buildPatterns(result)
	content := buildContextIgnore(groups)

	if !strings.Contains(content, "# ctx-ignore: generated by ctx-ignore scan") {
		t.Error("missing header")
	}
	if !strings.Contains(content, "# Generated:") {
		t.Error("missing date line")
	}
	if !strings.Contains(content, "# Lockfiles") {
		t.Error("missing lockfiles comment")
	}
	if !strings.Contains(content, "package-lock.json") {
		t.Error("missing lockfile pattern")
	}
	if !strings.Contains(content, "*_test.go") {
		t.Error("missing test file pattern")
	}
}

func TestBuildDerivedIgnoreHasNoPreamble(t *testing.T) {
	result := testResult()
	groups := buildPatterns(result)
	content := buildDerivedIgnore(groups)

	if strings.Contains(content, "#") {
		t.Error("derived ignore should have no comments")
	}
	if !strings.Contains(content, "package-lock.json") {
		t.Error("missing lockfile pattern")
	}
	if !strings.Contains(content, "*_test.go") {
		t.Error("missing test file pattern")
	}
}

func TestGenerateDryRunWritesNoFiles(t *testing.T) {
	dir := t.TempDir()
	result := testResult()
	result.Root = dir

	opts := DefaultOptions()
	opts.DryRun = true
	opts.OutputDir = dir

	generated, err := Generate(result, opts)
	if err != nil {
		t.Fatal(err)
	}

	if len(generated) != 3 {
		t.Errorf("expected 3 generated names, got %d", len(generated))
	}

	// Verify no files were actually created
	for _, name := range []string{".contextignore", ".claudeignore", ".cursorignore"} {
		path := filepath.Join(dir, name)
		if _, err := os.Stat(path); err == nil {
			t.Errorf("dry run should not create %s", name)
		}
	}
}

func TestGenerateCreatesAllFiles(t *testing.T) {
	dir := t.TempDir()
	result := testResult()
	result.Root = dir

	opts := DefaultOptions()
	opts.OutputDir = dir

	generated, err := Generate(result, opts)
	if err != nil {
		t.Fatal(err)
	}

	if len(generated) != 3 {
		t.Fatalf("expected 3 generated, got %d: %v", len(generated), generated)
	}

	for _, name := range []string{".contextignore", ".claudeignore", ".cursorignore"} {
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("expected %s to exist: %v", name, err)
			continue
		}
		if !strings.Contains(string(data), "package-lock.json") {
			t.Errorf("%s missing pattern", name)
		}
	}
}

func TestPatchGitIgnoreNoDuplicates(t *testing.T) {
	dir := t.TempDir()
	gitignore := filepath.Join(dir, ".gitignore")

	// Write initial .gitignore that already has dist/
	if err := os.WriteFile(gitignore, []byte("node_modules/\ndist/\n"), 0644); err != nil {
		t.Fatal(err)
	}

	groups := []patternGroup{
		{comment: "test", patterns: []string{"node_modules/", "dist/", "coverage/"}},
	}

	if err := patchGitIgnore(dir, groups); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(gitignore)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	// coverage/ should be added, node_modules/ and dist/ should NOT be duplicated
	if strings.Count(content, "node_modules/") != 1 {
		t.Errorf("node_modules/ should appear exactly once, got:\n%s", content)
	}
	if strings.Count(content, "dist/") != 1 {
		t.Errorf("dist/ should appear exactly once, got:\n%s", content)
	}
	if !strings.Contains(content, "coverage/") {
		t.Error("coverage/ should be added")
	}
}

func TestPatchGitIgnoreSubstringNoFalsePositive(t *testing.T) {
	dir := t.TempDir()
	gitignore := filepath.Join(dir, ".gitignore")

	// "redistribution/" should NOT match pattern "dist/"
	if err := os.WriteFile(gitignore, []byte("redistribution/\n"), 0644); err != nil {
		t.Fatal(err)
	}

	groups := []patternGroup{
		{comment: "test", patterns: []string{"dist/"}},
	}

	if err := patchGitIgnore(dir, groups); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(gitignore)
	content := string(data)

	if !strings.Contains(content, "\ndist/\n") && !strings.HasSuffix(content, "\ndist/") {
		t.Errorf("dist/ should be added even when redistribution/ exists, got:\n%s", content)
	}
}
